<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Polkadot &amp; Substrate network adapter for Crypto.Net (SS58, Extrinsics, RPC)</Description>
    <PackageId>Crypto.Net.Polkadot</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Crypto.Net.Core\Crypto.Net.Core.csproj" />
    <ProjectReference Include="..\Crypto.Net.Wallet\Crypto.Net.Wallet.csproj" />
  </ItemGroup>
</Project>
