<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Solana network adapter for Crypto.Net (Ed25519, Base58, SystemProgram, Solana RPC)</Description>
    <PackageId>Crypto.Net.Solana</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Crypto.Net.Core\Crypto.Net.Core.csproj" />
    <ProjectReference Include="..\Crypto.Net.Wallet\Crypto.Net.Wallet.csproj" />
  </ItemGroup>
</Project>
